project:
  type: website
  output-dir: docs
website:
  title: "Leonardo D Nunes"
  favicon: logo\logo.svg
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    logo: logo\logo.svg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/leonardo-donato-nunes-754aa5b8/
        target: _blank
      - icon: github
        menu:
          - text: LeonardoNunes
            href:  https://github.com/LeonardoDonatoNunes
            target: _blank
          - text: Source Code
            href: https://github.com/LeonardoDonatoNunes/LeonardoNotes
            target: _blank
  sidebar:
    style: 'docked'
    search: true
    contents: 
      - section: "Python"
        contents: 
          - paginas/python/upsert_eficiente/upsert.qmd
      - section: "SQL"
        contents:
          - section: 'Postgres'
            contents:
              - paginas/sql/postgres/introducao.qmd
              - paginas/sql/postgres/listar_colunas.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



